#!/bin/bash

set -eux

ROOT="$(dirname `readlink -f $0`)"
MODULES="${ROOT}"/deployment_scripts/puppet/modules
TMP_DIR="${ROOT}"/tmp
mkdir -p "${MODULES}"
mkdir -p "${TMP_DIR}"
REPO_PATH='https://github.com/stackforge/fuel-library/tarball/f43d885914d74fbd062096763222f350f47480e1'
RPM_REPO="${ROOT}"/repositories/centos/
DEB_REPO="${ROOT}"/repositories/ubuntu/

wget -qO- "${REPO_PATH}" | \
    tar -C "${MODULES}" --strip-components=3 -zxvf - \
    stackforge-fuel-library-f43d885/deployment/puppet/{inifile,stdlib}

GLUSTER_RPM='http://download.gluster.org/pub/gluster/glusterfs/LATEST/CentOS/epel-5/x86_64/glusterfs-3.5.2-1.el5.x86_64.rpm'
wget -P $RPM_REPO $GLUSTER_RPM

apt-get download glusterfs-client
mv glusterfs-client* $DEB_REPO