#!/bin/bash

set -eux

ROOT="$(dirname `readlink -f $0`)"
MODULES="${ROOT}"/deployment_scripts/puppet/modules
TMP_DIR="${ROOT}"/tmp
mkdir -p "${MODULES}"
mkdir -p "${TMP_DIR}"
REPO_PATH='https://github.com/stackforge/fuel-library/tarball/f43d885914d74fbd062096763222f350f47480e1'
RPM_REPO="${ROOT}"/repositories/centos/
DEB_REPO="${ROOT}"/repositories/ubuntu/

wget -qO- "${REPO_PATH}" | \
    tar -C "${MODULES}" --strip-components=3 -zxvf - \
    stackforge-fuel-library-f43d885/deployment/puppet/{inifile,stdlib}

wget -P $RPM_REPO -nd -r -np --reject "index.html*" "http://osci-obs.vm.mirantis.net:82/centos-fuel-master-690/centos/x86_64/"
wget -P $DEB_REPO -nd -r -np --reject "index.html*" "http://osci-obs.vm.mirantis.net:82/ubuntu-fuel-master-691/ubuntu/amd64/"
