modes_metadata:
  ha_compact:
    description: "This configuration Deploys OpenStack ready for high availability (HA). Controller services are prepared for HA by setting up a base MySQL/Galera, RabbitMQ and HAProxy so that additional controllers can be deployed NOW, or scaled out LATER. 3 or more controllers are required for a true HA environment."
required_component_types:
  - hypervisor
  - network
  - storage
modes: ['ha_compact']
extensions: ['volume_manager', 'network_manager']
