attributes:
  metadata:
    label: "Database settings"
    weight: 90
  # Gathering variables from user about our DCP
  yaml_additional_config:
    type: "textarea"
    weight: 52
    value: |
      #Uncomment to enable remote DB:
      #remote_db: '10.20.99.1'
      #remote_db_password: 'secret'
      custom_mysql_setup_class: 'galera'
    label: "Additional config"
    description: "Just put here valid yaml" 
