#!/bin/bash

set -eux

ROOT="$(dirname `readlink -f $0`)"
MODULES="${ROOT}"/deployment_scripts/puppet/modules
TMP_DIR="${ROOT}"/tmp
mkdir -p "${MODULES}"
mkdir -p "${TMP_DIR}"
REPO_PATH='https://github.com/stackforge/fuel-library/tarball/f43d885914d74fbd062096763222f350f47480e1'

wget -qO- "${REPO_PATH}" | \
    tar -C "${MODULES}" --strip-components=3 -zxvf - \
    stackforge-fuel-library-f43d885/deployment/puppet/{inifile,stdlib}

RPM_REPO="${ROOT}"/repositories/centos/
RPM_REPO_URL="http://mirror.fuel-infra.org/fwm/6.0/centos/os/x86_64/Packages/"
RPM_PACKAGES="nfs-utils-lib-1.1.5-6.el6.x86_64.rpm
keyutils-1.4-4.el6.x86_64.rpm
libgssglue-0.1-11.el6.x86_64.rpm
nfs-utils-1.2.3-39.el6.x86_64.rpm
libevent-1.4.13-4.el6.x86_64.rpm
rpcbind-0.2.0-11.el6.x86_64.rpm
libtirpc-0.2.1-6.el6_5.2.x86_64.rpm"

DEB_REPO="${ROOT}"/repositories/ubuntu/
DEB_REPO_URL="http://mirror.fuel-infra.org/fwm/6.0/ubuntu/pool/main/"
DEB_PACKAGES="libtirpc1_0.2.2-5_amd64.deb
libgssglue1_0.3-4ubuntu0.1_amd64.deb
libevent-2.0-5_2.0.16-stable-1_amd64.deb
nfs-common_1.2.5-3ubuntu3.1_amd64.deb
libnfsidmap2_0.25-1ubuntu2_amd64.deb
rpcbind_0.2.0-7ubuntu1.2_amd64.deb"

download_packages () {
    local REPO_PATH=$1
    local REPO_URL=$2
    local PACKAGES=$3

    for PACKAGE in ${PACKAGES}; do
        wget -P ${REPO_PATH} -nc ${REPO_URL}${PACKAGE}
    done
}

download_packages ${RPM_REPO} ${RPM_REPO_URL} "$RPM_PACKAGES"
download_packages ${DEB_REPO} ${DEB_REPO_URL} "$DEB_PACKAGES"