- id: fuel_plugin_example_v3
  type: group
  role: [fuel_plugin_example_v3]
  tasks:
    - hiera
    - globals
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    strategy:
      type: parallel

- id: fuel_plugin_example_v3-controller-deployment
  type: puppet
  groups: [primary-controller, controller]
  required_for: [connectivity_tests, deploy_end]
  requires: [netconfig, deploy_start]
  parameters:
    puppet_manifest: "deploy.pp"
    puppet_modules: "."
    timeout: 3600

- id: fuel_plugin_example_v3-deployment
  type: puppet
  groups: [fuel_plugin_example_v3]
  required_for: [deploy_end]
  requires: [deploy_start]
  parameters:
    puppet_manifest: "deploy.pp"
    puppet_modules: "."
    timeout: 3600
    retries: 10

- id: fuel_plugin_example_v3-post-deployment-sh
  type: shell
  role: [fuel_plugin_example_v3]
  required_for: [post_deployment_end]
  requires: [post_deployment_start]
  parameters:
    cmd: bash deploy.sh
    retries: 3
    interval: 20
    timeout: 180

# This legacy tasks will be applied on controller nodes
- id: fuel_plugin_example_v3-legacy-1
  role: ['primary-controller', 'controller']
  stage: post_deployment
  type: shell
  parameters:
    cmd: bash deploy.sh
    timeout: 42

- id: fuel_plugin_example_v3-legacy-2
  role: '*'
  stage: pre_deployment/100
  type: shell
  parameters:
    cmd: echo all > /tmp/plugin+100.all
    timeout: 42

- id: fuel_plugin_example_v3-legacy-3
  role: '*'
  stage: pre_deployment/+101.0
  type: shell
  parameters:
    cmd: echo all > /tmp/plugin+100.0.all
    timeout: 42

- id: fuel_plugin_example_v3-legacy-4
  role: '*'
  stage: pre_deployment/-100
  type: shell
  parameters:
    cmd: echo all > /tmp/plugin-100.all
    timeout: 42

- id: fuel_plugin_example_v3-legacy-5
  role: [compute]
  stage: pre_deployment/-101
  type: puppet
  parameters:
    puppet_manifest: "deploy.pp"
    puppet_modules: "."
    timeout: 3600
    retries: 2
